package Telas.Cads;

import Conexao.OperacoesDB;
import static Conexao.OperacoesDB.Medico.veriMed;
import Conexao.OperacoesDB.Paciente;
import static Conexao.OperacoesDB.Paciente.veriPac;
import Telas.TelaInicial;
import java.util.List;
import javax.swing.*;

public class TelaCadPac extends javax.swing.JFrame {

    public TelaCadPac() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imageMedSy = new ImageIcon("medsyimg.png");
        ImageIcon imagehome = new ImageIcon("homeicon.png");
        lblMedsy.setIcon(imageMedSy);
        lblIconHome.setIcon(imagehome);
        btnCadPacAtualizar.setEnabled(false);
        btnCadPacApaga.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblMedsy = new javax.swing.JLabel();
        lblIconHome = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtCadPacEnd = new javax.swing.JTextField();
        txtCadPacNasc = new javax.swing.JTextField();
        txtCadPacNome = new javax.swing.JTextField();
        txtCadPacCpf = new javax.swing.JTextField();
        txtCadPacTele = new javax.swing.JTextField();
        btnCadPacCadastrar = new javax.swing.JButton();
        btnCadPacApaga = new javax.swing.JButton();
        txtCadPacEmail1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCadPacAtualizar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Principal");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        lblMedsy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblIconHome.setBackground(new java.awt.Color(255, 255, 255));
        lblIconHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblIconHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(131, 189, 241));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Nome");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(131, 189, 241));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Data De nascimento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(131, 189, 241));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Edereço");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(131, 189, 241));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Email");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(131, 189, 241));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("Telefone");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(131, 189, 241));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setText("Cpf");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtCadPacEnd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCadPacEnd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCadPacEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadPacEndActionPerformed(evt);
            }
        });
        txtCadPacEnd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadPacEndKeyPressed(evt);
            }
        });

        txtCadPacNasc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCadPacNasc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCadPacNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadPacNascActionPerformed(evt);
            }
        });
        txtCadPacNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadPacNascKeyPressed(evt);
            }
        });

        txtCadPacNome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCadPacNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCadPacNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadPacNomeActionPerformed(evt);
            }
        });
        txtCadPacNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadPacNomeKeyPressed(evt);
            }
        });

        txtCadPacCpf.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCadPacCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCadPacCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadPacCpfActionPerformed(evt);
            }
        });
        txtCadPacCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadPacCpfKeyPressed(evt);
            }
        });

        txtCadPacTele.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCadPacTele.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCadPacTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadPacTeleActionPerformed(evt);
            }
        });
        txtCadPacTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadPacTeleKeyPressed(evt);
            }
        });

        btnCadPacCadastrar.setBackground(new java.awt.Color(131, 189, 241));
        btnCadPacCadastrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadPacCadastrar.setText("CADASTRAR");
        btnCadPacCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacCadastrarActionPerformed(evt);
            }
        });

        btnCadPacApaga.setBackground(new java.awt.Color(131, 189, 241));
        btnCadPacApaga.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadPacApaga.setText("EXCLUÍR");
        btnCadPacApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacApagaActionPerformed(evt);
            }
        });

        txtCadPacEmail1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCadPacEmail1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCadPacEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadPacEmail1ActionPerformed(evt);
            }
        });
        txtCadPacEmail1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadPacEmail1KeyPressed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(131, 189, 241));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCadPacAtualizar.setBackground(new java.awt.Color(131, 189, 241));
        btnCadPacAtualizar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadPacAtualizar.setText("ATUALIZAR");
        btnCadPacAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnCadPacAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadPacCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadPacApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadPacNasc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadPacEnd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadPacCpf)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadPacNome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadPacEmail1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadPacTele))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(txtCadPacCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtCadPacNome))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCadPacEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(txtCadPacNasc))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(txtCadPacTele))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCadPacEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadPacApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadPacCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadPacAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadPacApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacApagaActionPerformed
         String cpfUser = txtCadPacCpf.getText(); 
 OperacoesDB.Paciente pac = new OperacoesDB.Paciente(cpfUser, "", "", "", "", "");  
   pac.deletePac(cpfUser);
   
        JOptionPane.showMessageDialog(null, "Cadastro excluído com sucesso!");
        btnCadPacCadastrar.setEnabled(true);
        btnCadPacAtualizar.setEnabled(false);
        btnCadPacApaga.setEnabled(false);
    }//GEN-LAST:event_btnCadPacApagaActionPerformed

    private void btnCadPacCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacCadastrarActionPerformed
         String NOMEP= "";
        String CPFP= " ";
        String EMAILP= " ";
        String NASCP= " ";
        String TELEFONEP= " ";
        String ENDERECOP= " ";
      
  

         NOMEP=  txtCadPacNome.getText();
                 System.out.println(NOMEP);

         CPFP=  txtCadPacCpf.getText();
                 System.out.println(CPFP);

         EMAILP = txtCadPacEmail1.getText();
                 System.out.println(EMAILP);

         NASCP = txtCadPacNasc.getText();
                 System.out.println(NASCP);

         TELEFONEP = txtCadPacTele.getText();
                 System.out.println(TELEFONEP);

         ENDERECOP = txtCadPacEnd.getText();
                 System.out.println(ENDERECOP);
                 Paciente pac1 = new Paciente(NOMEP, CPFP,  EMAILP, NASCP, TELEFONEP, ENDERECOP);
                 pac1.insertPac(NOMEP, CPFP,  EMAILP, NASCP, TELEFONEP, ENDERECOP);
      String veriCpfS = pac1.getCpfP();
                 if(veriCpfS.equals(CPFP)){
             JOptionPane.showMessageDialog(null,"Cadastro Bem Sucedido");
             System.out.println(veriCpfS);
             System.out.println(CPFP);
             
         }
    }//GEN-LAST:event_btnCadPacCadastrarActionPerformed

    private void txtCadPacTeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadPacTeleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacTeleKeyPressed

    private void txtCadPacTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadPacTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacTeleActionPerformed

    private void txtCadPacCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadPacCpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacCpfKeyPressed

    private void txtCadPacCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadPacCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacCpfActionPerformed

    private void txtCadPacNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadPacNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacNomeKeyPressed

    private void txtCadPacNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadPacNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacNomeActionPerformed

    private void txtCadPacNascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadPacNascKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacNascKeyPressed

    private void txtCadPacNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadPacNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacNascActionPerformed

    private void txtCadPacEndKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadPacEndKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacEndKeyPressed

    private void txtCadPacEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadPacEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacEndActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblIconHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseClicked
        // TODO add your handling code here:
        int sn = JOptionPane.showConfirmDialog(rootPane, "Deseja relamente ir para a tela inicial?");
        System.out.println(sn);
        if (sn == 0) {
            TelaInicial tlIni = new TelaInicial();
            tlIni.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Clicou pq então? fdp");
        }
        /*TelaConfLog Telaconflog = new TelaConfLog();
        Telaconflog.setVisible(true);*/
    }//GEN-LAST:event_lblIconHomeMouseClicked

    private void txtCadPacEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadPacEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacEmail1ActionPerformed

    private void txtCadPacEmail1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadPacEmail1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadPacEmail1KeyPressed
private boolean teste;
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
 String cpfUser = txtCadPacCpf.getText();
             teste = veriPac(cpfUser);
         if(teste==true){
           Paciente pac2 = new Paciente("", "", "", "", "", "");
            List<OperacoesDB.Paciente> SelectPac = pac2.SelectPac(cpfUser);
            OperacoesDB.Paciente pc = SelectPac.get(0);
            String nome = pc.getNome();
    
            txtCadPacNome.setText(""+nome);
            String email = pc.getEmailP();
            txtCadPacNasc.setText("");  
            txtCadPacEmail1.setText(""+email);
            String nasc = pc.getNascP();
            txtCadPacNasc.setText("");
            txtCadPacNasc.setText(""+nasc);
            String tele = pc.getTeleP();
            txtCadPacTele.setText("");
            txtCadPacTele.setText(tele);
            String ende = pc.getEnderecoP();
            txtCadPacEnd.setText("");
            txtCadPacEnd.setText(tele);
          JOptionPane.showMessageDialog(null,"Cadastro encontrado com sucesso");
         }else {
          JOptionPane.showMessageDialog(null,"Cadastro não encontrado");
         }
        btnCadPacAtualizar.setEnabled(true);
        btnCadPacApaga.setEnabled(true);
        btnCadPacCadastrar.setEnabled(false);
     
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCadPacAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacAtualizarActionPerformed
       String NOMEP= "";
        String CPFP= " ";
        String EMAILP= " ";
        String NASCP= " ";
        String TELEFONEP= " ";
        String ENDERECOP= " ";
      
  

         NOMEP=  txtCadPacNome.getText();
                 System.out.println(NOMEP);

         CPFP=  txtCadPacCpf.getText();
                 System.out.println(CPFP);

         EMAILP = txtCadPacEmail1.getText();
                 System.out.println(EMAILP);

         NASCP = txtCadPacNasc.getText();
                 System.out.println(NASCP);

         TELEFONEP = txtCadPacTele.getText();
                 System.out.println(TELEFONEP);

         ENDERECOP = txtCadPacEnd.getText();
                 System.out.println(ENDERECOP);
                 String cpfUser = txtCadPacCpf.getText();
                  Paciente pac = new Paciente(cpfUser, "", "", "", "", "");  
   pac.updatePac( NOMEP, cpfUser,  EMAILP, NASCP, TELEFONEP, ENDERECOP);
        JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso!");
        btnCadPacCadastrar.setEnabled(true);
        btnCadPacAtualizar.setEnabled(false);
        btnCadPacApaga.setEnabled(false);
    }//GEN-LAST:event_btnCadPacAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadPac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadPacApaga;
    private javax.swing.JButton btnCadPacAtualizar;
    private javax.swing.JButton btnCadPacCadastrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIconHome;
    private javax.swing.JLabel lblMedsy;
    private javax.swing.JTextField txtCadPacCpf;
    private javax.swing.JTextField txtCadPacEmail1;
    private javax.swing.JTextField txtCadPacEnd;
    private javax.swing.JTextField txtCadPacNasc;
    private javax.swing.JTextField txtCadPacNome;
    private javax.swing.JTextField txtCadPacTele;
    // End of variables declaration//GEN-END:variables
}
