package Telas.Cads;

import Conexao.OperacoesDB;

import Conexao.OperacoesDB.Medico;
import static Conexao.OperacoesDB.Medico.nomeMed;
import static Conexao.OperacoesDB.Medico.veriMed;
import Conexao.OperacoesDB.Secretaria;
import static Conexao.OperacoesDB.Secretaria.veriSec;
import Telas.TelaInicial;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public class TelaCadSecMed extends javax.swing.JFrame {

    public TelaCadSecMed() {
        initComponents();
        tela = "med";
        this.setLocationRelativeTo(null);
        ImageIcon imageMedSy = new ImageIcon("medsyimg.png");
        ImageIcon imagehome = new ImageIcon("homeicon.png");
        lblMedsy.setIcon(imageMedSy);
        lblIconHome.setIcon(imagehome);
        BtnMed.setEnabled(false);
        btnCadSecMedAtualiza.setEnabled(false);
        btnCadSecMedApaga.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblMedsy = new javax.swing.JLabel();
        lblIconHome = new javax.swing.JLabel();
        BtnCrm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnEspec = new javax.swing.JButton();
        txtEnde = new javax.swing.JTextField();
        txtSenhaConf = new javax.swing.JTextField();
        txtCrm = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        txtEspec = new javax.swing.JTextField();
        btnCadMedCadastrar = new javax.swing.JButton();
        btnCadSecMedApaga = new javax.swing.JButton();
        txtNasc = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        BtnSec = new javax.swing.JButton();
        BtnMed = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtSenha1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCadSecMedAtualiza = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela De Cadastro de Funcionários");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        lblMedsy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblIconHome.setBackground(new java.awt.Color(255, 255, 255));
        lblIconHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblIconHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseClicked(evt);
            }
        });

        BtnCrm.setBackground(new java.awt.Color(131, 189, 241));
        BtnCrm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnCrm.setText("CRM");
        BtnCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrmActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(131, 189, 241));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Cpf");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(131, 189, 241));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Data De nascimento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(131, 189, 241));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Endereço");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(131, 189, 241));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Email");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(131, 189, 241));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("Telefone");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(131, 189, 241));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setText("Nome");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(131, 189, 241));
        jButton10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton10.setText("Confirmação de senha");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnEspec.setBackground(new java.awt.Color(131, 189, 241));
        btnEspec.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEspec.setText("Especialidade");
        btnEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecActionPerformed(evt);
            }
        });

        txtEnde.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEnde.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEnde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndeActionPerformed(evt);
            }
        });
        txtEnde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEndeKeyPressed(evt);
            }
        });

        txtSenhaConf.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSenhaConf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSenhaConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaConfActionPerformed(evt);
            }
        });
        txtSenhaConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaConfKeyPressed(evt);
            }
        });

        txtCrm.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCrm.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrmActionPerformed(evt);
            }
        });
        txtCrm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCrmKeyPressed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        txtCpf.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfKeyPressed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        txtTele.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTele.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleActionPerformed(evt);
            }
        });
        txtTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTeleKeyPressed(evt);
            }
        });

        txtEspec.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEspec.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecActionPerformed(evt);
            }
        });
        txtEspec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEspecKeyPressed(evt);
            }
        });

        btnCadMedCadastrar.setBackground(new java.awt.Color(131, 189, 241));
        btnCadMedCadastrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadMedCadastrar.setText("CADASTRAR");
        btnCadMedCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedCadastrarActionPerformed(evt);
            }
        });

        btnCadSecMedApaga.setBackground(new java.awt.Color(131, 189, 241));
        btnCadSecMedApaga.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadSecMedApaga.setText("EXCLUÍR");
        btnCadSecMedApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadSecMedApagaActionPerformed(evt);
            }
        });

        txtNasc.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNasc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascActionPerformed(evt);
            }
        });
        txtNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNascKeyPressed(evt);
            }
        });

        BtnSec.setBackground(new java.awt.Color(131, 189, 241));
        BtnSec.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSec.setText("Funcionário");
        BtnSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSecActionPerformed(evt);
            }
        });

        BtnMed.setBackground(new java.awt.Color(131, 189, 241));
        BtnMed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnMed.setText("Medico");
        BtnMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMedActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(131, 189, 241));
        jButton9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton9.setText("Senha");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtSenha1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSenha1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha1ActionPerformed(evt);
            }
        });
        txtSenha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenha1KeyPressed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(131, 189, 241));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Alternar");

        btnCadSecMedAtualiza.setBackground(new java.awt.Color(131, 189, 241));
        btnCadSecMedAtualiza.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadSecMedAtualiza.setText("ATUALIZAR");
        btnCadSecMedAtualiza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadSecMedAtualizaMouseClicked(evt);
            }
        });
        btnCadSecMedAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadSecMedAtualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnMed, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEspec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCrm)
                            .addComponent(txtEspec)
                            .addComponent(txtSenhaConf)
                            .addComponent(txtSenha1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCpf)
                                        .addGap(18, 18, 18)))
                                .addComponent(btnBuscar))
                            .addComponent(txtNome)
                            .addComponent(txtEmail)
                            .addComponent(txtNasc)
                            .addComponent(txtTele)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnde)))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnCadSecMedAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadMedCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadSecMedApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnMed, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSec, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtCpf)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(txtNome))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(txtTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnde)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSenhaConf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton10))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEspec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEspec, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadSecMedAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadMedCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadSecMedApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(249, 249, 249))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascKeyPressed

    private void txtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascActionPerformed

    private void btnCadSecMedApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadSecMedApagaActionPerformed
        // TODO add your handling code here:
  //      JOptionPane.showMessageDialog(null, "Cadastro excluído com sucesso!");
  if(tela=="sec"){
  String cpfUser = txtCpf.getText(); 
 Secretaria scs = new Secretaria(cpfUser, "", "", "", "", "", "");  
   scs.deleteSec(cpfUser);
      JOptionPane.showMessageDialog(null,"Cadastro De Secretária Deletado");
  }
  if(tela=="med"){
        String cpfUser = txtCpf.getText(); 
 Medico mds = new Medico(cpfUser, "", "", "", "", "", "","","");  
   mds.deleteMed(cpfUser);
   JOptionPane.showMessageDialog(null,"Cadastro De Médico Deletado");
  }
  btnCadMedCadastrar.setEnabled(true);
        btnCadSecMedAtualiza.setEnabled(false);
        btnCadSecMedApaga.setEnabled(false);
    }//GEN-LAST:event_btnCadSecMedApagaActionPerformed

    private void btnCadMedCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedCadastrarActionPerformed
        // TODO add your handling code here:
        /*  String veriNome = txtNome.getText();
        String veriCpf = txtCpf.getText();
        String veriEmail = txtEmail.getText();
        String veriNasc = txtNasc.getText();    
        String veriTele = txtTele.getText();
        String veriEnde = txtEnde.getText();
         */

        if (!txtSenha1.getText().equals(txtSenhaConf.getText())) {
            JOptionPane.showMessageDialog(null, "As senhas não coencidem");

        } else {

            if (tela == "med") {

                String nomeMed = "";
                String cpfMed = " ";
                String emailMed = " ";
                String nascMed = " ";
                String telefoneMed = " ";
                String enderecoMed = " ";
                String crm = " ";
                String especialidade = " ";
                String senhaMed = " ";

                nomeMed = txtNome.getText();
                System.out.println(nomeMed);

                cpfMed = txtCpf.getText();
                System.out.println(cpfMed);

                emailMed = txtEmail.getText();
                System.out.println(emailMed);

                nascMed = txtNasc.getText();
                System.out.println(nascMed);

                telefoneMed = txtTele.getText();
                System.out.println(telefoneMed);

                enderecoMed = txtEnde.getText();
                System.out.println(enderecoMed);

                crm = txtCrm.getText();
                System.out.println(crm);

                especialidade = txtEspec.getText();
                System.out.println(especialidade);

                senhaMed = txtSenha1.getText();
                int Numacess = 1;
                Medico md1 = new Medico(nomeMed, cpfMed, emailMed, nascMed, telefoneMed, enderecoMed, crm, especialidade, senhaMed);
                md1.insertMed(nomeMed, cpfMed, emailMed, nascMed, telefoneMed, enderecoMed, crm, especialidade, senhaMed);
                md1.insertLogin(nomeMed, cpfMed, senhaMed, Numacess);
                String veriCpfM = md1.getCpf();

                if (veriCpfM.equals(cpfMed)) {
                    JOptionPane.showMessageDialog(null, "Cadastro Bem Sucedido");
                    System.out.println(veriCpfM);
                    System.out.println(cpfMed);

                }

            }
            if (tela == "sec") {
                String NOMES = "";
                String CPFSecre = " ";
                String EMAILS = " ";
                String NASCS = " ";
                String TELEFONEs = " ";
                String ENDERECOs = " ";
                String SENHAS = " ";
                String funcao = " ";

                System.out.println(NOMES);

                NOMES = txtNome.getText();
                System.out.println(NOMES);

                CPFSecre = txtCpf.getText();
                System.out.println(CPFSecre);

                EMAILS = txtEmail.getText();
                System.out.println(EMAILS);

                NASCS = txtNasc.getText();
                System.out.println(NASCS);

                TELEFONEs = txtTele.getText();
                System.out.println(TELEFONEs);

                ENDERECOs = txtEnde.getText();
                System.out.println(ENDERECOs);

                SENHAS = txtSenha1.getText();
                System.out.println(SENHAS);

                int Numacess = 2;
                System.out.println(funcao.getClass());
                Secretaria sc1 = new Secretaria(NOMES, CPFSecre, EMAILS, NASCS, TELEFONEs, ENDERECOs, SENHAS);
                // sc1.insertSec(NOMES,CPFSecre, EMAILS,NASCS,TELEFONEs,ENDERECOs,SENHAS,funcao);
                sc1.insertSec(NOMES, CPFSecre, EMAILS, NASCS, TELEFONEs, ENDERECOs, SENHAS);
                sc1.insertLogin(NOMES, CPFSecre, SENHAS, Numacess);
                String veriCpfS = sc1.getCpfS();

                if (veriCpfS.equals(CPFSecre)) {
                    JOptionPane.showMessageDialog(null, "Cadastro Bem Sucedido");
                    System.out.println(veriCpfS);
                    System.out.println(CPFSecre);

                }

            }
            /*
        public void insert(String nome, String email) {
            String sql = "INSERT INTO usuario (nome,email) VALUES (?,?)";
            try (Connection conn = ConexaoDB.getConexao();
                PreparedStatement stmt = conn.prepareStatement(sql)) {

                stmt.setString(1, nome);
                stmt.setString(2, email);
                stmt.executeUpdate();

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
      
             */
        }

    }//GEN-LAST:event_btnCadMedCadastrarActionPerformed

    private void txtEspecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecKeyPressed

    private void txtEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecActionPerformed

    private void txtTeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleKeyPressed

    private void txtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfKeyPressed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCrmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCrmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrmKeyPressed

    private void txtCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrmActionPerformed

    private void txtSenhaConfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaConfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaConfKeyPressed

    private void txtSenhaConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaConfActionPerformed

    private void txtEndeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndeKeyPressed

    private void txtEndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndeActionPerformed

    private void btnEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspecActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCrmActionPerformed

    private void lblIconHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseClicked
        // TODO add your handling code here:
        int sn = JOptionPane.showConfirmDialog(rootPane, "Deseja relamente ir para a tela inicial?");
        //StxtCrmystem.out.println(sn);
        if (sn == 0) {
            TelaInicial tlIni = new TelaInicial();
            tlIni.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Retornando a tela");
        }
        /*TelaConfLog Telaconflog = new TelaConfLog();
        Telaconflog.setVisible(true);*/
    }//GEN-LAST:event_lblIconHomeMouseClicked
    public String tela = "";
    private void BtnSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSecActionPerformed
        // TODO add your handling code here:
        BtnCrm.setVisible(false);
        btnEspec.setVisible(false);
        txtCrm.setVisible(false);
        txtEspec.setVisible(false);
        BtnSec.setEnabled(false);
        BtnMed.setEnabled(true);
        tela = "sec";
  txtCpf.setText("");
  txtNome.setText("");  
  txtEmail.setText("");  
  txtNasc.setText("");
  txtTele.setText("");
  txtEnde.setText("");
  txtSenha1.setText("");
  txtSenhaConf.setText("");


    }//GEN-LAST:event_BtnSecActionPerformed

    private void BtnMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMedActionPerformed
        // TODO add your handling code here:
        BtnCrm.setVisible(true);
        btnEspec.setVisible(true);
        txtCrm.setVisible(true);
        txtEspec.setVisible(true);
        BtnMed.setEnabled(false);
        BtnSec.setEnabled(true);
        tela = "med";
   txtCpf.setText("");
  txtNome.setText("");  
  txtEmail.setText("");  
  txtNasc.setText("");
  txtTele.setText("");
  txtEnde.setText("");
  txtCrm.setText("");
  txtSenha1.setText("");
  txtSenhaConf.setText("");
  txtEspec.setText("");
    }//GEN-LAST:event_BtnMedActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha1ActionPerformed

    private void txtSenha1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenha1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha1KeyPressed
private boolean teste;
private boolean teste2;

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        btnCadSecMedAtualiza.setEnabled(true);
        btnCadSecMedApaga.setEnabled(true);
        btnCadMedCadastrar.setEnabled(false);
        String cpfUser = txtCpf.getText();
         teste = veriMed(cpfUser);
         teste2 = veriSec(cpfUser);

        if (teste == true) {
            btnCadSecMedAtualiza.setEnabled(true);

            Medico mds = new Medico("", "", "", "", "", "", "", "", "");
            List<Medico> selectMed = mds.SelectMed(cpfUser);
            Medico med = selectMed.get(0);
            String nome = med.getNome();
            txtNome.setText("");  
            txtNome.setText(""+nome);
            String email = med.getEmailM();
            txtEmail.setText("");  
            txtEmail.setText(""+email);
            String nasc = med.getnascM();
            txtNasc.setText("");
            txtNasc.setText(""+nasc);
            String tele = med.getTelefoneM();
            txtTele.setText("");
            txtTele.setText(tele);
            String ende = med.getEnderecoM();
            txtEnde.setText("");
            txtEnde.setText(ende);
            String crm = med.getCrm();
            txtCrm.setText("");
            txtCrm.setText(crm);
            String senha = med.getSenhaM();
            txtSenha1.setText("");
            txtSenha1.setText(senha);
            txtSenhaConf.setText("");
            txtSenhaConf.setText(senha);
            
            String espec = med.getEspec();
             txtEspec.setText("");
            txtEspec.setText(espec);
           
  

            System.out.println(nome);
            System.out.println(email);
            System.out.println(nasc);

            JOptionPane.showMessageDialog(null, "Cadastro Encontrado");

        }
        if (teste2 == true) {
            
            btnCadSecMedAtualiza.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Cadastro Encontrado");
            Secretaria scs = new Secretaria("", "", "", "", "", "", "");
            List<Secretaria> selectS = scs.SelectSec(cpfUser);
    
            OperacoesDB.Secretaria scd = selectS.get(0);
              
            String nomeS = scd.getNomeS();
            txtNome.setText(nomeS);
            String emailS = scd.getEmailS();
            txtEmail.setText(emailS);
            String nascS = scd.getNascS();
            txtNasc.setText(nascS);
            String teleS = scd.getTeleS();
            txtTele.setText(teleS);
           String endeS = scd.getEndeS();
            txtEnde.setText(endeS);
            String senhaS = scd.getSenhaS();
            txtSenha1.setText(senhaS);
            txtSenhaConf.setText(senhaS);

        } else {
            JOptionPane.showMessageDialog(null, "Cadastro não encontrado");
        }
        System.out.println(teste2);
    }//GEN-LAST:event_btnBuscarActionPerformed
public boolean getTeste(){
    return teste;
}
public boolean getTeste2(){
    return teste2;
}
    private void btnCadSecMedAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadSecMedAtualizaActionPerformed

          
       if (!txtSenha1.getText().equals(txtSenhaConf.getText())) {
            JOptionPane.showMessageDialog(null, "As senhas não coencidem");

        } else {

            if (tela == "med") {
  

                String nomeMed = "";
                String cpfMed = " ";
                String emailMed = " ";
                String nascMed = " ";
                String telefoneMed = " ";
                String enderecoMed = " ";
                String crm = " ";
                String especialidade = " ";
                String senhaMed = " ";

                nomeMed = txtNome.getText();
                System.out.println(nomeMed);

                cpfMed = txtCpf.getText();
                System.out.println(cpfMed);

                emailMed = txtEmail.getText();
                System.out.println(emailMed);

                nascMed = txtNasc.getText();
                System.out.println(nascMed);

                telefoneMed = txtTele.getText();
                System.out.println(telefoneMed);

                enderecoMed = txtEnde.getText();
                System.out.println(enderecoMed);

                crm = txtCrm.getText();
                System.out.println(crm);

                especialidade = txtEspec.getText();
                System.out.println(especialidade);
     
                senhaMed = txtSenha1.getText();
            String cpfUser = txtCpf.getText();  
 Medico mds = new Medico(cpfUser, "", "", "", "", "", "","","");  
   mds.updateMed(nomeMed,cpfMed, cpfUser, emailMed, nascMed, telefoneMed, enderecoMed, crm, especialidade, senhaMed);


              

            }
       }
       if (tela == "sec") {
                String NOMES = "";
                String CPFSecre = " ";
                String EMAILS = " ";
                String NASCS = " ";
                String TELEFONEs = " ";
                String ENDERECOs = " ";
                String SENHAS = " ";
                String funcao = " ";

                System.out.println(NOMES);

                NOMES = txtNome.getText();
                System.out.println(NOMES);

                CPFSecre = txtCpf.getText();
                System.out.println(CPFSecre);

                EMAILS = txtEmail.getText();
                System.out.println(EMAILS);

                NASCS = txtNasc.getText();
                System.out.println(NASCS);

                TELEFONEs = txtTele.getText();
                System.out.println(TELEFONEs);

                ENDERECOs = txtEnde.getText();
                System.out.println(ENDERECOs);

                SENHAS = txtSenha1.getText();
                System.out.println(SENHAS);
        
            


            }

     //   btnCadMedCadastrar.setEnabled(true);
       // btnCadSecMedAtualiza.setEnabled(false);
     //   btnCadSecMedApaga.setEnabled(false);

       
    }//GEN-LAST:event_btnCadSecMedAtualizaActionPerformed
private int contadorCliques =0;
    private void btnCadSecMedAtualizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadSecMedAtualizaMouseClicked
    contadorCliques++;
        if(contadorCliques==1){
        JOptionPane.showMessageDialog(null, "Modifique os campos, que deseja atualizar");
   }
        if (contadorCliques == 2) {
        // Ação a ser executada após 2 cliques
    
        contadorCliques = 0; // Reseta o contador
         if (!txtSenha1.getText().equals(txtSenhaConf.getText())) {
            JOptionPane.showMessageDialog(null, "As senhas não coencidem");

        } else {

            if (tela == "med") {

                String nomeMed = "";
                String cpfMed = " ";
                String emailMed = " ";
                String nascMed = " ";
                String telefoneMed = " ";
                String enderecoMed = " ";
                String crm = " ";
                String especialidade = " ";
                String senhaMed = " ";

                nomeMed = txtNome.getText();
                System.out.println(nomeMed);

                cpfMed = txtCpf.getText();
                System.out.println(cpfMed);

                emailMed = txtEmail.getText();
                System.out.println(emailMed);

                nascMed = txtNasc.getText();
                System.out.println(nascMed);

                telefoneMed = txtTele.getText();
                System.out.println(telefoneMed);

                enderecoMed = txtEnde.getText();
                System.out.println(enderecoMed);

                crm = txtCrm.getText();
                System.out.println(crm);

                especialidade = txtEspec.getText();
                System.out.println(especialidade);

                senhaMed = txtSenha1.getText();
                int Numacess = 1;
                Medico md1 = new Medico(nomeMed, cpfMed, emailMed, nascMed, telefoneMed, enderecoMed, crm, especialidade, senhaMed);
                md1.insertMed(nomeMed, cpfMed, emailMed, nascMed, telefoneMed, enderecoMed, crm, especialidade, senhaMed);
                md1.insertLogin(nomeMed, cpfMed, senhaMed, Numacess);
                String veriCpfM = md1.getCpf();

                if (veriCpfM.equals(cpfMed)) {
                    JOptionPane.showMessageDialog(null, "Cadastro Bem Sucedido");
                    System.out.println(veriCpfM);
                    System.out.println(cpfMed);

                }

            }
       }
       if (tela == "sec") {
                String NOMES = "";
                String CPFSecre = " ";
                String EMAILS = " ";
                String NASCS = " ";
                String TELEFONEs = " ";
                String ENDERECOs = " ";
                String SENHAS = " ";
                String funcao = " ";

                System.out.println(NOMES);

                NOMES = txtNome.getText();
                System.out.println(NOMES);

                CPFSecre = txtCpf.getText();
                System.out.println(CPFSecre);

                EMAILS = txtEmail.getText();
                System.out.println(EMAILS);

                NASCS = txtNasc.getText();
                System.out.println(NASCS);

                TELEFONEs = txtTele.getText();
                System.out.println(TELEFONEs);

                ENDERECOs = txtEnde.getText();
                System.out.println(ENDERECOs);

                SENHAS = txtSenha1.getText();
                System.out.println(SENHAS);

                int Numacess = 2;
                System.out.println(funcao.getClass());
                Secretaria sc1 = new Secretaria(NOMES, CPFSecre, EMAILS, NASCS, TELEFONEs, ENDERECOs, SENHAS);
                // sc1.insertSec(NOMES,CPFSecre, EMAILS,NASCS,TELEFONEs,ENDERECOs,SENHAS,funcao);
                sc1.insertSec(NOMES, CPFSecre, EMAILS, NASCS, TELEFONEs, ENDERECOs, SENHAS);
                sc1.insertLogin(NOMES, CPFSecre, SENHAS, Numacess);
                String veriCpfS = sc1.getCpfS();

                if (veriCpfS.equals(CPFSecre)) {
                    JOptionPane.showMessageDialog(null, "Cadastro Bem Sucedido");
                    System.out.println(veriCpfS);
                    System.out.println(CPFSecre);

                }

            }

     //   btnCadMedCadastrar.setEnabled(true);
       // btnCadSecMedAtualiza.setEnabled(false);
     //   btnCadSecMedApaga.setEnabled(false);
  
    }  
    }//GEN-LAST:event_btnCadSecMedAtualizaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadSecMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadSecMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadSecMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadSecMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadSecMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrm;
    private javax.swing.JButton BtnMed;
    private javax.swing.JButton BtnSec;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadMedCadastrar;
    private javax.swing.JButton btnCadSecMedApaga;
    private javax.swing.JButton btnCadSecMedAtualiza;
    private javax.swing.JButton btnEspec;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIconHome;
    private javax.swing.JLabel lblMedsy;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCrm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnde;
    private javax.swing.JTextField txtEspec;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha1;
    private javax.swing.JTextField txtSenhaConf;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables

}
