/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.sql.Array;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/*
import static jdk.nashorn.internal.objects.ArrayBufferView.length;
 */
/**
 *
 * @author User
 */
public class TelaCalendario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalendario
     */
    public TelaCalendario() {

        initComponents();

    }
    int[] dias = {1, 4, 5, 6, 7, 8, 11, 12, 13, 14,
        15, 18, 19, 20, 21, 22, 25, 26, 27, 28, 29};

    public List<Integer> numerosOrdenados = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DiaQuatro = new javax.swing.JButton();
        DiaOnze = new javax.swing.JButton();
        DiaDezoito = new javax.swing.JButton();
        DiaVinteecinco = new javax.swing.JButton();
        DiaCinco = new javax.swing.JButton();
        DiaDoze = new javax.swing.JButton();
        DiaDezenove = new javax.swing.JButton();
        DiaOito = new javax.swing.JButton();
        DiaQuinze = new javax.swing.JButton();
        DiaVinteedois = new javax.swing.JButton();
        DiaVinteenove = new javax.swing.JButton();
        btnMark = new javax.swing.JButton();
        lblDias = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DiaVinteeseis = new javax.swing.JButton();
        DiaSeis = new javax.swing.JButton();
        DiaTreze = new javax.swing.JButton();
        DiaVinte = new javax.swing.JButton();
        DiaVinteesete = new javax.swing.JButton();
        DiaSete = new javax.swing.JButton();
        DiaQuatorze = new javax.swing.JButton();
        DiaVinteeum = new javax.swing.JButton();
        DiaVinteeoito = new javax.swing.JButton();
        DiaUm = new javax.swing.JButton();
        DiaDois = new javax.swing.JButton();
        DiaTres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quarta-Feira");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quinta-Feira");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sexta-Feira");

        DiaQuatro.setText("4");
        DiaQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaQuatroActionPerformed(evt);
            }
        });

        DiaOnze.setText("11");
        DiaOnze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaOnzeActionPerformed(evt);
            }
        });

        DiaDezoito.setText("18");
        DiaDezoito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaDezoitoActionPerformed(evt);
            }
        });

        DiaVinteecinco.setText("25");
        DiaVinteecinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteecincoActionPerformed(evt);
            }
        });

        DiaCinco.setText("5");
        DiaCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaCincoActionPerformed(evt);
            }
        });

        DiaDoze.setText("12");
        DiaDoze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaDozeActionPerformed(evt);
            }
        });

        DiaDezenove.setText("19");
        DiaDezenove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaDezenoveActionPerformed(evt);
            }
        });

        DiaOito.setText("8");
        DiaOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaOitoActionPerformed(evt);
            }
        });

        DiaQuinze.setText("15");
        DiaQuinze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaQuinzeActionPerformed(evt);
            }
        });

        DiaVinteedois.setText("22");
        DiaVinteedois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteedoisActionPerformed(evt);
            }
        });

        DiaVinteenove.setText("29");
        DiaVinteenove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteenoveActionPerformed(evt);
            }
        });

        btnMark.setText("SELECIONAR");
        btnMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkActionPerformed(evt);
            }
        });

        lblDias.setText("Dias");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Segunda-Feira");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Terça-Feira");

        DiaVinteeseis.setText("26");
        DiaVinteeseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteeseisActionPerformed(evt);
            }
        });

        DiaSeis.setText("6");
        DiaSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaSeisActionPerformed(evt);
            }
        });

        DiaTreze.setText("13");
        DiaTreze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaTrezeActionPerformed(evt);
            }
        });

        DiaVinte.setText("20");
        DiaVinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteActionPerformed(evt);
            }
        });

        DiaVinteesete.setText("27");
        DiaVinteesete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteeseteActionPerformed(evt);
            }
        });

        DiaSete.setText("7");
        DiaSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaSeteActionPerformed(evt);
            }
        });

        DiaQuatorze.setText("14");
        DiaQuatorze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaQuatorzeActionPerformed(evt);
            }
        });

        DiaVinteeum.setText("21");
        DiaVinteeum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteeumActionPerformed(evt);
            }
        });

        DiaVinteeoito.setText("28");
        DiaVinteeoito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaVinteeoitoActionPerformed(evt);
            }
        });

        DiaUm.setText("1");
        DiaUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaUmActionPerformed(evt);
            }
        });

        DiaDois.setText("2");
        DiaDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaDoisActionPerformed(evt);
            }
        });

        DiaTres.setText("3");
        DiaTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaTresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DiaOnze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaDezoito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaVinteecinco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiaQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DiaDoze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaDezenove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaVinteeseis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DiaTreze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaVinte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaVinteesete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiaSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DiaQuatorze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaVinteeum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiaVinteeoito, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiaSete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DiaUm, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DiaDois, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMark)
                        .addGap(94, 94, 94)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DiaOito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DiaQuinze, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addComponent(DiaVinteedois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DiaVinteenove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaUm)
                            .addComponent(DiaDois)
                            .addComponent(DiaTres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(DiaSete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaQuatorze)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaVinteeum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaVinteeoito))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DiaSeis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaTreze)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaVinte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaVinteesete))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(DiaQuatro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaOnze)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaDezoito)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaVinteecinco))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(DiaCinco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaDoze)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaDezenove)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaVinteeseis)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DiaOito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaQuinze)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaVinteedois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiaVinteenove)))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMark)
                    .addComponent(lblDias))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DiaVinteecincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteecincoActionPerformed
        numerosOrdenados.add(25);

    }//GEN-LAST:event_DiaVinteecincoActionPerformed

    private void DiaVinteeseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteeseisActionPerformed
        numerosOrdenados.add(26);

    }//GEN-LAST:event_DiaVinteeseisActionPerformed

    private void DiaVinteeseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteeseteActionPerformed
        numerosOrdenados.add(27);

    }//GEN-LAST:event_DiaVinteeseteActionPerformed

    private void DiaVinteeoitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteeoitoActionPerformed
        numerosOrdenados.add(28);

    }//GEN-LAST:event_DiaVinteeoitoActionPerformed

    private void DiaVinteenoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteenoveActionPerformed
        numerosOrdenados.add(29);

    }//GEN-LAST:event_DiaVinteenoveActionPerformed

    private void DiaUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaUmActionPerformed
        numerosOrdenados.add(1);
    }//GEN-LAST:event_DiaUmActionPerformed

    private void DiaQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaQuatroActionPerformed
        numerosOrdenados.add(4);

      }//GEN-LAST:event_DiaQuatroActionPerformed

    private void DiaCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaCincoActionPerformed
        numerosOrdenados.add(5);
      }//GEN-LAST:event_DiaCincoActionPerformed

    private void DiaSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaSeisActionPerformed
        numerosOrdenados.add(6);
    }//GEN-LAST:event_DiaSeisActionPerformed

    private void DiaSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaSeteActionPerformed
        numerosOrdenados.add(7);
      }//GEN-LAST:event_DiaSeteActionPerformed

    private void DiaOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaOitoActionPerformed
        numerosOrdenados.add(8);

     }//GEN-LAST:event_DiaOitoActionPerformed

    private void DiaOnzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaOnzeActionPerformed
        numerosOrdenados.add(11);

    }//GEN-LAST:event_DiaOnzeActionPerformed

    private void DiaDozeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaDozeActionPerformed
        numerosOrdenados.add(12);

    }//GEN-LAST:event_DiaDozeActionPerformed

    private void DiaTrezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaTrezeActionPerformed
        numerosOrdenados.add(13);
    }//GEN-LAST:event_DiaTrezeActionPerformed

    private void DiaQuatorzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaQuatorzeActionPerformed
        numerosOrdenados.add(14);

    }//GEN-LAST:event_DiaQuatorzeActionPerformed

    private void DiaQuinzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaQuinzeActionPerformed
        numerosOrdenados.add(15);

    }//GEN-LAST:event_DiaQuinzeActionPerformed

    private void DiaDezoitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaDezoitoActionPerformed
        numerosOrdenados.add(18);

    }//GEN-LAST:event_DiaDezoitoActionPerformed

    private void DiaDezenoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaDezenoveActionPerformed
        numerosOrdenados.add(19);

    }//GEN-LAST:event_DiaDezenoveActionPerformed

    private void DiaVinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteActionPerformed

        numerosOrdenados.add(20);
    }//GEN-LAST:event_DiaVinteActionPerformed

    private void DiaVinteeumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteeumActionPerformed
        numerosOrdenados.add(21);

    }//GEN-LAST:event_DiaVinteeumActionPerformed

    private void DiaVinteedoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaVinteedoisActionPerformed
        numerosOrdenados.add(22);

    }//GEN-LAST:event_DiaVinteedoisActionPerformed
    public static int maiorNumero;
    public static int menorNumero;
    public static int diasT;
    private void btnMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkActionPerformed
        Collections.sort(numerosOrdenados);
        maiorNumero = Collections.max(numerosOrdenados);
        menorNumero = Collections.min(numerosOrdenados);
        System.out.println("menor " + menorNumero);
        System.out.println("maior " + maiorNumero);

        for (Integer numero : numerosOrdenados) {
            System.out.println(numero);
        }
        int contador = 0;
        int primeiraposição = -1;
        int tamanho = numerosOrdenados.size();
        for (int i = 0; i < numerosOrdenados.size(); i++) {
            int numero = numerosOrdenados.get(i);

            if (numero < menorNumero) {
                menorNumero = numero;
            }

            if (numero > maiorNumero) {
                maiorNumero = numero;
            }
        }

// Contar os números que estão entre o menor e o maior
        for (int i = 0; i < numerosOrdenados.size(); i++) {
            int numero = numerosOrdenados.get(i);

            // Verifica se o número está entre o menor e o maior
            if (numero > menorNumero && numero < maiorNumero) {
                contador++;
            }
        }
        System.out.println("Existem " + contador + " números entre o menor e o maior número.");
        diasT = contador + 2;
        this.dispose();
    }//GEN-LAST:event_btnMarkActionPerformed

    private void DiaDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaDoisActionPerformed
        // TODO add your handling code here:
        numerosOrdenados.add(2);
    }//GEN-LAST:event_DiaDoisActionPerformed

    private void DiaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaTresActionPerformed
        // TODO add your handling code here:
        numerosOrdenados.add(3);
    }//GEN-LAST:event_DiaTresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiaCinco;
    private javax.swing.JButton DiaDezenove;
    private javax.swing.JButton DiaDezoito;
    private javax.swing.JButton DiaDois;
    private javax.swing.JButton DiaDoze;
    private javax.swing.JButton DiaOito;
    private javax.swing.JButton DiaOnze;
    private javax.swing.JButton DiaQuatorze;
    private javax.swing.JButton DiaQuatro;
    private javax.swing.JButton DiaQuinze;
    private javax.swing.JButton DiaSeis;
    private javax.swing.JButton DiaSete;
    private javax.swing.JButton DiaTres;
    private javax.swing.JButton DiaTreze;
    private javax.swing.JButton DiaUm;
    private javax.swing.JButton DiaVinte;
    private javax.swing.JButton DiaVinteecinco;
    private javax.swing.JButton DiaVinteedois;
    private javax.swing.JButton DiaVinteenove;
    private javax.swing.JButton DiaVinteeoito;
    private javax.swing.JButton DiaVinteeseis;
    private javax.swing.JButton DiaVinteesete;
    private javax.swing.JButton DiaVinteeum;
    private javax.swing.JButton btnMark;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDias;
    // End of variables declaration//GEN-END:variables
}
