package Telas;

import Conexao.OperacoesDB;
import Conexao.OperacoesDB.Consultas;
import Telas.TelaCalendario;
import Conexao.OperacoesDB.Horarios;
import Telas.TelaInicial;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

public class TelaAgendamento extends javax.swing.JFrame {

    public TelaAgendamento() {

        initComponents();
/*
        int parameter = TelaCalendario.diasT;
        int[] numeros = {parameter};
        for (int i = 0; i < numeros.size(); i++) {
            JComboMedDia.addItem(numeros.get(i));  // Adiciona cada número ao JComboBox
        }

        /*   int maiorNum = TelaCalendario.maiorNumero;
        System.out.println(maiorNum);
        for(int dia=1; dia < maiorNum; dia++){
           System.out.println(dia);
                JcomboMedDia.addItem(dia); 
            
        }
         */
        this.setLocationRelativeTo(null);
        ImageIcon imageMedSy = new ImageIcon("medsyimg.png");
        ImageIcon imagehome = new ImageIcon("homeicon.png");
        lblMedsy.setIcon(imageMedSy);
        lblIconHome.setIcon(imagehome);
        // carregarDias(JcomboMedDia);     
        //    System.out.println(dia);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblMedsy = new javax.swing.JLabel();
        lblIconHome = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtConPacCpf = new javax.swing.JTextField();
        txtConPacNome = new javax.swing.JTextField();
        BTNMARCAR = new javax.swing.JButton();
        txtConPacEmail1 = new javax.swing.JTextField();
        javax.swing.JComboBox<String> JcomboMedHora = new javax.swing.JComboBox<>();
        JComboMedDia = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela De Agendamento");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        lblMedsy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblIconHome.setBackground(new java.awt.Color(255, 255, 255));
        lblIconHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblIconHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(131, 189, 241));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Especialidade");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(131, 189, 241));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Dia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(131, 189, 241));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Médico");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(131, 189, 241));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("Horário");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(131, 189, 241));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setText("Paciente");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtConPacCpf.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtConPacCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtConPacCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConPacCpfActionPerformed(evt);
            }
        });
        txtConPacCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConPacCpfKeyPressed(evt);
            }
        });

        txtConPacNome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtConPacNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtConPacNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConPacNomeActionPerformed(evt);
            }
        });
        txtConPacNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConPacNomeKeyPressed(evt);
            }
        });

        BTNMARCAR.setBackground(new java.awt.Color(131, 189, 241));
        BTNMARCAR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BTNMARCAR.setText("MARCAR");
        BTNMARCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMARCARActionPerformed(evt);
            }
        });

        txtConPacEmail1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtConPacEmail1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtConPacEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConPacEmail1ActionPerformed(evt);
            }
        });
        txtConPacEmail1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConPacEmail1KeyPressed(evt);
            }
        });

        JcomboMedHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));

        JComboMedDia.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JComboMedDia, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JcomboMedHora, 0, 259, Short.MAX_VALUE))
                            .addComponent(txtConPacNome)
                            .addComponent(txtConPacCpf)
                            .addComponent(txtConPacEmail1))))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTNMARCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedsy, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConPacNome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConPacCpf))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConPacEmail1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JComboMedDia, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JcomboMedHora, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(BTNMARCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNMARCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMARCARActionPerformed
        String PAC = "";
        String ESPEC = " ";
        String MED = " ";
        String dia = " ";
        int DIA = 0;
        String HORARIO = " ";

        PAC = txtConPacNome.getText();
        System.out.println(PAC);

        ESPEC = txtConPacCpf.getText();
        System.out.println(ESPEC);

        MED = txtConPacEmail1.getText();
        System.out.println(MED);

        //dia = (String) JcomboMedDia.getSelectedItem();
        DIA = Integer.parseInt(dia);
        System.out.println(DIA);

        //  HORARIO =(String) JcomboMedHora.getSelectedItem();
        System.out.println(HORARIO);

        Consultas cons1 = new Consultas(PAC, ESPEC, MED, DIA, HORARIO);
        cons1.insertCon(PAC, ESPEC, MED, DIA, HORARIO);
        String veriNome = cons1.getPac();

        if (veriNome.equals(PAC)) {
            JOptionPane.showMessageDialog(null, "Agendamento Bem Sucedido");
            System.out.println(veriNome);
            System.out.println(PAC);
        }
    }//GEN-LAST:event_BTNMARCARActionPerformed

    private void txtConPacNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPacNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConPacNomeKeyPressed

    private void txtConPacNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConPacNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConPacNomeActionPerformed

    private void txtConPacCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPacCpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConPacCpfKeyPressed

    private void txtConPacCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConPacCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConPacCpfActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblIconHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseClicked
        // TODO add your handling code here:
        int sn = JOptionPane.showConfirmDialog(rootPane, "Deseja relamente ir para a tela inicial?");
        System.out.println(sn);
        if (sn == 0) {
            TelaInicial tlIni = new TelaInicial();
            tlIni.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Retorne");
        }
        /*TelaConfLog Telaconflog = new TelaConfLog();
        Telaconflog.setVisible(true);*/
    }//GEN-LAST:event_lblIconHomeMouseClicked

    private void txtConPacEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConPacEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConPacEmail1ActionPerformed

    private void txtConPacEmail1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPacEmail1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConPacEmail1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendamento().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNMARCAR;
    private javax.swing.JComboBox<Integer> JComboMedDia;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIconHome;
    private javax.swing.JLabel lblMedsy;
    private javax.swing.JTextField txtConPacCpf;
    private javax.swing.JTextField txtConPacEmail1;
    private javax.swing.JTextField txtConPacNome;
    // End of variables declaration//GEN-END:variables
}
